# This is a basic workflow to help you get started with Actions

name: Create-release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install 7zip
        run: sudo apt install p7zip-full

      # Runs a set of commands using the runners shell
      - name: Create mod archive
        run: |
          modname="insects_world_$(git tag)"
          mv insects_world_dev/insects_world_dev.xml "insects_world_dev/$modname.xml"
          mv insects_world_dev/ "$modname/"
          7z a -t7z "$modname.7z" "$modname/"

      - name: Upload To Github Release
        # You may pin to the exact commit or the version.
        # uses: xresloader/upload-to-github-release@98857380fc282f8075a62c6af230fe92bd93aff8
        uses: xresloader/upload-to-github-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The files or file patterns to upload. You can upload multiple files by split them by semicolon. You can use the glob pattern to find the files.
          file: "*.7z"
          overwrite: true
          tags: true
          update_latest_release: true

